import type { Metadata } from "next";
import { Geist_Mono, Nunito_Sans, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import AuthProvider from "@/components/auth/AuthProvider"; // ⬅️ baru

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        nunitoSans.variable,
        geistMono.variable,
        "font-sans",
        geist.variable,
      )}>
      <body className="min-h-full flex flex-col">
        <AuthProvider>{children}</AuthProvider>{" "}
        {/* ⬅️ baru, bungkus children */}
      </body>
    </html>
  );
}
